### ISSUE TITLE
Add requirements file

### ISSUE THREAD

**Issue by tupini07** [DelgadoJosh/WanderingInnScraper#1]
Thanks for the nice project! Now I can finally read the amazing _Wandering Inn_ on my Kindle :D 

I suggest that you add a `requirements.txt` file so that whoever wants to execute the script directly will know exactly what dependencies they need to install to make it work.

**Comment by DelgadoJosh** [comment]
Excellent idea! I hadn't thought of that since I was thinking of people primarily using the executable, but I had forgotten many users may prefer not to use the executable.

My apologies to only seeing this now, I'm relatively new to posting things publicly. I'll see exactly what dependencies I have and update the repository.

**Comment by DelgadoJosh** [comment]
Alright, I installed a fresh copy of python, and installed the minimal set of dependencies until the script worked. I added a `dependencies.md` file to the `Scripts` folder, along with the instructions for the pip commands to install them.

Hope this helps!

**Comment by tupini07** [comment]
thanks!
